2021-03-24 17:02:55,488 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 17:07:41,479 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 17:44:33,772 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 17:44:40,527 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:09:41,264 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:10:28,879 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:10:40,961 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:10:44,629 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:20:16,658 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:20:17,986 ERROR: Exception on /user/Bridget [GET] [in /Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/bwiffler/dev/rising/app/routes.py", line 78, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/bwiffler/dev/rising/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/bwiffler/dev/rising/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/bwiffler/dev/rising/app/templates/user.html", line 11, in block "content"
    <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'followed'
2021-03-24 18:21:13,466 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:27:13,220 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:29:19,726 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:34:54,242 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:40:49,536 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:40:51,954 ERROR: Exception on /index [GET] [in /Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/bwiffler/dev/rising/app/routes.py", line 28, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2021-03-24 18:55:51,414 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 18:55:53,368 ERROR: Exception on /index [GET] [in /Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/bwiffler/dev/rising/app/routes.py", line 28, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2021-03-24 18:57:02,471 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 19:03:41,291 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 19:41:23,332 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 19:48:52,718 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
2021-03-24 19:48:56,907 ERROR: Exception on /user/Bridget [GET] [in /Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/bwiffler/dev/rising/app/routes.py", line 85, in user
    return render_template('user.html', user=user, posts=posts,
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/bwiffler/dev/rising/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/bwiffler/dev/rising/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/bwiffler/dev/rising/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/bwiffler/dev/rising/app/templates/user.html", line 33, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2021-03-24 19:49:46,390 INFO: Microblog startup [in /Users/bwiffler/dev/rising/app/__init__.py:46]
